spring.application.name=backend

# Supabase Database Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ca-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.vafnhunjvminmtijtyki
# IMPORTANT: Replace [YOUR-PASSWORD] with your actual Supabase database password
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect\
  
spring.jackson.property-naming-strategy=SNAKE_CASE
